# Use Python 3.10 slim as a base image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Python application code into the container
COPY . .

# Install the required Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the application will run on
EXPOSE 5000

# Command to run the master node (Flask app)
CMD ["python", "master.py"]
